### ISSUE TITLE
BUG Backend when making too many request 

### ISSUE THREAD

**Issue by SamuelGuillemet** [Clochette-AbsINThe/clochette#105]
Je pense que quand trop de requêtes sont envoyées au backend il plante
---
```
2023-01-14 21:05:30 ERROR:    Exception in ASGI application
2023-01-14 21:05:30 Traceback (most recent call last):
2023-01-14 21:05:30   File "/usr/local/lib/python3.11/site-packages/anyio/streams/memory.py", line 94, in receive
2023-01-14 21:05:30     return self.receive_nowait()
2023-01-14 21:05:30            ^^^^^^^^^^^^^^^^^^^^^
2023-01-14 21:05:30   File "/usr/local/lib/python3.11/site-packages/anyio/streams/memory.py", line 89, in receive_nowait
2023-01-14 21:05:30     raise WouldBlock
2023-01-14 21:05:30 anyio.WouldBlock
2023-01-14 21:05:30 
2023-01-14 21:05:30 During handling of the above exception, another exception occurred:
2023-01-14 21:05:30 
2023-01-14 21:05:30 Traceback (most recent call last):
2023-01-14 21:05:30   File "/usr/local/lib/python3.11/site-packages/starlette/middleware/base.py", line 77, in call_next
2023-01-14 21:05:30     message = await recv_stream.receive()
2023-01-14 21:05:30               ^^^^^^^^^^^^^^^^^^^^^^^^^^^
2023-01-14 21:05:30   File "/usr/local/lib/python3.11/site-packages/anyio/streams/memory.py", line 114, in receive
2023-01-14 21:05:30     raise EndOfStream
2023-01-14 21:05:30 anyio.EndOfStream
2023-01-14 21:05:30 
2023-01-14 21:05:30 During handling of the above exception, another exception occurred:
2023-01-14 21:05:30 
2023-01-14 21:05:30 Traceback (most recent call last):
2023-01-14 21:05:30   File "/code/app/core/middleware.py", line 70, in dispatch
2023-01-14 21:05:30     return await call_next(request)
2023-01-14 21:05:30            ^^^^^^^^^^^^^^^^^^^^^^^^
2023-01-14 21:05:30   File "/usr/local/lib/python3.11/site-packages/starlette/middleware/base.py", line 80, in call_next
2023-01-14 21:05:30     raise app_exc
2023-01-14 21:05:30   File "/usr/local/lib/python3.11/site-packages/starlette/middleware/base.py", line 69, in coro
2023-01-14 21:05:30     await self.app(scope, receive_or_disconnect, send_no_error)
2023-01-14 21:05:30   File "/usr/local/lib/python3.11/site-packages/starlette/middleware/exceptions.py", line 79, in __call__
2023-01-14 21:05:30     raise exc
2023-01-14 21:05:30   File "/usr/local/lib/python3.11/site-packages/starlette/middleware/exceptions.py", line 68, in __call__
2023-01-14 21:05:30     await self.app(scope, receive, sender)
2023-01-14 21:05:30   File "/usr/local/lib/python3.11/contextlib.py", line 222, in __aexit__
2023-01-14 21:05:30     await self.gen.athrow(typ, value, traceback)
2023-01-14 21:05:30   File "/usr/local/lib/python3.11/site-packages/fastapi/concurrency.py", line 36, in contextmanager_in_threadpool
2023-01-14 21:05:30     raise e
2023-01-14 21:05:30 sqlalchemy.exc.TimeoutError: QueuePool limit of size 5 overflow 10 reached, connection timed out, timeout 30.00 (Background on this error at: https://sqlalche.me/e/14/3o7r)
2023-01-14 21:05:30 
2023-01-14 21:05:30 During handling of the above exception, another exception occurred:
2023-01-14 21:05:30 
2023-01-14 21:05:30 Traceback (most recent call last):
2023-01-14 21:05:30   File "/usr/local/lib/python3.11/site-packages/uvicorn/protocols/http/httptools_impl.py", line 419, in run_asgi
2023-01-14 21:05:30     result = await app(  # type: ignore[func-returns-value]
2023-01-14 21:05:30              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2023-01-14 21:05:30   File "/usr/local/lib/python3.11/site-packages/uvicorn/middleware/proxy_headers.py", line 78, in __call__
2023-01-14 21:05:30     return await self.app(scope, receive, send)
2023-01-14 21:05:30            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2023-01-14 21:05:30   File "/usr/local/lib/python3.11/site-packages/fastapi/applications.py", line 270, in __call__
2023-01-14 21:05:30     await super().__call__(scope, receive, send)
2023-01-14 21:05:30   File "/usr/local/lib/python3.11/site-packages/starlette/applications.py", line 124, in __call__
2023-01-14 21:05:30     await self.middleware_stack(scope, receive, send)
2023-01-14 21:05:30   File "/usr/local/lib/python3.11/site-packages/starlette/middleware/errors.py", line 184, in __call__
2023-01-14 21:05:30     raise exc
2023-01-14 21:05:30   File "/usr/local/lib/python3.11/site-packages/starlette/middleware/errors.py", line 162, in __call__
2023-01-14 21:05:30     await self.app(scope, receive, _send)
2023-01-14 21:05:30   File "/usr/local/lib/python3.11/site-packages/starlette/middleware/trustedhost.py", line 34, in __call__
2023-01-14 21:05:30     await self.app(scope, receive, send)
2023-01-14 21:05:30   File "/usr/local/lib/python3.11/site-packages/starlette/middleware/base.py", line 106, in __call__
2023-01-14 21:05:30     response = await self.dispatch_func(request, call_next)
2023-01-14 21:05:30                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2023-01-14 21:05:30   File "/code/app/core/middleware.py", line 73, in dispatch
2023-01-14 21:05:30     body = await self.get_body(request)
2023-01-14 21:05:30            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2023-01-14 21:05:30   File "/code/app/core/middleware.py", line 56, in get_body
2023-01-14 21:05:30     body = await request.body()
2023-01-14 21:05:30            ^^^^^^^^^^^^^^^^^^^^
2023-01-14 21:05:30   File "/usr/local/lib/python3.11/site-packages/starlette/requests.py", line 234, in body
2023-01-14 21:05:30     async for chunk in self.stream():
2023-01-14 21:05:30   File "/usr/local/lib/python3.11/site-packages/starlette/requests.py", line 228, in stream
2023-01-14 21:05:30     raise ClientDisconnect()
2023-01-14 21:05:30 starlette.requests.ClientDisconnect
```
Le bug arrive quand j'essaye de charger les stats de transactions :
![image](https://user-images.githubusercontent.com/60295745/212494564-91f9547a-1603-4a01-9a89-556677ee9e00.png)

**Comment by SamuelGuillemet** [comment]
https://github.com/tiangolo/fastapi/issues/3205

**Comment by xanode** [comment]
Seems to be resolved since #112
