### ISSUE TITLE
InvalidRequestError: Entity namespace for "outofstock" has no property "out_of_stock_item_id"

### ISSUE THREAD

**Issue by xanode** [Clochette-AbsINThe/clochette#60]
# InvalidRequestError: Entity namespace for "outofstock" has no property "out_of_stock_item_id"

DELETE http://clochette.dev/api/v1/out_of_stock_item/1

## Request headers
- **connection**: close
- **host**: clochette.dev
- **x-real-ip**: 172.19.0.1
- **forwarded**: for=172.19.0.1
- **x-forwarded-for**: 172.19.0.1
- **x-forwarded-proto**: https
- **x-forwarded-host**: clochette.dev
- **x-forwarded-port**: 443
- **user-agent**: Mozilla/5.0 (X11; Linux x86_64; rv:106.0) Gecko/20100101 Firefox/106.0
- **accept**: application/json
- **accept-language**: fr,fr-FR;q=0.8,en-US;q=0.5,en;q=0.3
- **accept-encoding**: gzip, deflate, br
- **referer**: https://clochette.dev/docs
- **origin**: https://clochette.dev
- **dnt**: 1
- **sec-fetch-dest**: empty
- **sec-fetch-mode**: cors
- **sec-fetch-site**: same-origin

## Request body
```

```

## Exception traceback
```
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/sqlalchemy/sql/base.py", line 1694, in _entity_namespace_key
    return getattr(ns, key)
           ^^^^^^^^^^^^^^^^
AttributeError: type object 'OutOfStock' has no attribute 'out_of_stock_item_id'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/code/app/core/middleware.py", line 28, in dispatch
    return await call_next(request)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/starlette/middleware/base.py", line 80, in call_next
    raise app_exc
  File "/usr/local/lib/python3.11/site-packages/starlette/middleware/base.py", line 69, in coro
    await self.app(scope, receive_or_disconnect, send_no_error)
  File "/usr/local/lib/python3.11/site-packages/starlette/middleware/exceptions.py", line 79, in __call__
    raise exc
  File "/usr/local/lib/python3.11/site-packages/starlette/middleware/exceptions.py", line 68, in __call__
    await self.app(scope, receive, sender)
  File "/usr/local/lib/python3.11/contextlib.py", line 222, in __aexit__
    await self.gen.athrow(typ, value, traceback)
  File "/usr/local/lib/python3.11/site-packages/fastapi/concurrency.py", line 36, in contextmanager_in_threadpool
    raise e
sqlalchemy.exc.InvalidRequestError: Entity namespace for "outofstock" has no property "out_of_stock_item_id"

```

**Comment by xanode** [comment]
L'erreur vient de la :
https://github.com/Clochette-AbsINThe/clochette/blob/01c9d3add399ce70ac2fcc52e0c0ebfb5f5bd3ce/backend/app/api/v1/endpoints/out_of_stock_item.py#L69

Ça devrait être :
```python
if out_of_stocks.query(db, limit=1, item_id=out_of_stock_item_id):
```
