### ISSUE TITLE
Error when MIGRATE is True

### ISSUE THREAD

**Issue by SamuelGuillemet** [Clochette-AbsINThe/clochette#68]
```
ERROR:    Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/starlette/routing.py", line 671, in lifespan
    async with self.lifespan_context(app):
  File "/usr/local/lib/python3.11/site-packages/starlette/routing.py", line 566, in __aenter__
    await self._router.startup()
  File "/usr/local/lib/python3.11/site-packages/starlette/routing.py", line 648, in startup
    await handler()
  File "/code/app/main.py", line 89, in run_migrations
    raise e
  File "/code/app/main.py", line 54, in run_migrations
    cur.execute(
psycopg2.errors.ObjectInUse: database "clochette" is being accessed by other users
DETAIL:  There is 1 other session using the database.
```

**Comment by xanode** [comment]
Sur la branche `dev_backend-auth` :
https://github.com/Clochette-AbsINThe/clochette/blob/2ba14ea236bfe11154978d628d1737e8efdea173/backend/app/main.py#L38-L93
Il manque un `break` pour terminer la boucle, donc forcément ça plante...
