### ISSUE TITLE
UnboundLocalError: cannot access local variable 'payload' where it is not associated with a value

### ISSUE THREAD

**Issue by xanode** [Clochette-AbsINThe/clochette#69]
# UnboundLocalError: cannot access local variable 'payload' where it is not associated with a value

GET http://clochette.dev/api/v1/auth/me

## Request headers
- **connection**: close
- **host**: clochette.dev
- **x-real-ip**: 172.19.0.1
- **forwarded**: for=172.19.0.1
- **x-forwarded-for**: 172.19.0.1
- **x-forwarded-proto**: https
- **x-forwarded-host**: clochette.dev
- **x-forwarded-port**: 443
- **user-agent**: Mozilla/5.0 (X11; Linux x86_64; rv:106.0) Gecko/20100101 Firefox/106.0
- **accept**: application/json
- **accept-language**: fr,fr-FR;q=0.8,en-US;q=0.5,en;q=0.3
- **accept-encoding**: gzip, deflate, br
- **referer**: https://clochette.dev/docs
- **authorization**: Bearer undefined
- **dnt**: 1
- **sec-fetch-dest**: empty
- **sec-fetch-mode**: cors
- **sec-fetch-site**: same-origin

## Request body
```

```

## Exception traceback
```
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/anyio/streams/memory.py", line 94, in receive
    return self.receive_nowait()
           ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/anyio/streams/memory.py", line 89, in receive_nowait
    raise WouldBlock
anyio.WouldBlock

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/starlette/middleware/base.py", line 77, in call_next
    message = await recv_stream.receive()
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/anyio/streams/memory.py", line 114, in receive
    raise EndOfStream
anyio.EndOfStream

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/code/app/core/middleware.py", line 28, in dispatch
    return await call_next(request)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/starlette/middleware/base.py", line 80, in call_next
    raise app_exc
  File "/usr/local/lib/python3.11/site-packages/starlette/middleware/base.py", line 69, in coro
    await self.app(scope, receive_or_disconnect, send_no_error)
  File "/usr/local/lib/python3.11/site-packages/starlette/middleware/exceptions.py", line 79, in __call__
    raise exc
  File "/usr/local/lib/python3.11/site-packages/starlette/middleware/exceptions.py", line 68, in __call__
    await self.app(scope, receive, sender)
  File "/usr/local/lib/python3.11/contextlib.py", line 222, in __aexit__
    await self.gen.athrow(typ, value, traceback)
  File "/usr/local/lib/python3.11/site-packages/fastapi/concurrency.py", line 36, in contextmanager_in_threadpool
    raise e
UnboundLocalError: cannot access local variable 'payload' where it is not associated with a value

```

**Comment by xanode** [comment]
Test

**Comment by xanode** [comment]
Test, labels are there.
